[project]
authors = [
    "Leandro Lacerda Campos <15185896+leandrolcampos@users.noreply.github.com>",
]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "MPFR-based testing for Mojo 🔥"
name = "mpfr-for-mojo"
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]
version = "0.1.0"

[dependencies]
max = "==25.1.0.dev2024121405"

[feature.test.tasks]
test = { cmd = "mojo test -I utils test", env = { MPFR_LIBRARY_DIR = "$CONDA_PREFIX/lib" } }

[feature.test.dependencies]
mpfr = ">=4.2,<4.3"

[environments]
default = { solve-group = "default" }
test = { features = ["test"], solve-group = "default" }
